#include "bsp_led.h"

void LED_GPIO_Init(void)
{
	GPIO_InitTypeDef LED_GPIO_INIT;
	__HAL_RCC_GPIOA_CLK_ENABLE();

	LED_GPIO_INIT.Mode = GPIO_MODE_OUTPUT_PP;
	LED_GPIO_INIT.Pin = GPIO_PIN_1;
	LED_GPIO_INIT.Pull = GPIO_PULLDOWN;
	LED_GPIO_INIT.Speed = GPIO_SPEED_FREQ_LOW;

	HAL_GPIO_Init(GPIOA, &LED_GPIO_INIT);
}